<template>
  <Tabs>
    <Tab
      title="Préférences"
      anchor="preferences"
    >
      <Preferences></Preferences>
    </Tab>
    <Tab
      title="Securité"
      anchor="security"
    >
      <Security></Security>
    </Tab>
  </Tabs>
</template>
