name: Deploy to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PITAYA }}

    - name: Git pull
      run: |
        ssh -o StrictHostKeyChecking=no github@90.0.8.199 -vvv 'echo "Changing directory"' 
        
    - name: Executing deploy script on remote machine
      run: |
        ssh -o StrictHostKeyChecking=no github@90.0.8.199 'sh ~/pitayahub/walletaya/repo/scripts/deploy.sh'
