name: Deploy to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PITAYA }}

    - name: Git pull
      run: |
        ssh -o StrictHostKeyChecking=no -p 5999 pitaya@90.0.8.199 'cd /var/www/bunkapp/Walletaya/repo && git reset --hard origin/main' 
        
    - name: Executing deploy script on remote machine
      run: |
        ssh -o StrictHostKeyChecking=no -p 5999 pitaya@90.0.8.199 'sh /var/www/bunkapp/Walletaya/repo/scripts/deploy.sh'
