name: Deploy to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PITAYA }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no github@192.168.1.19 'bash -s' < ~/pitayahub/walletaya/scripts/deploy.sh
